"""add_current_capital

Revision ID: 3ffe64f1f3fd
Revises: db1ac8836ab5
Create Date: 2025-12-03 17:26:13.068331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ffe64f1f3fd'
down_revision = 'db1ac8836ab5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_strategies', sa.Column('current_capital', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_strategies', 'current_capital')
    # ### end Alembic commands ###
