"""add_user_secrets_and_strategy_fields

Revision ID: 4fc131d3fb82
Revises: e579286c6a05
Create Date: 2025-12-02 15:24:39.095545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc131d3fb82'
down_revision = 'e579286c6a05'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_secrets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_name', sa.String(), nullable=False),
    sa.Column('encrypted_value', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('strategies', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('strategies', sa.Column('category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'category')
    op.drop_column('strategies', 'is_favorite')
    op.drop_table('user_secrets')
    # ### end Alembic commands ###
