"""Add trading_agents and agent_logs tables

Revision ID: 5fc8c9fb17c0
Revises: 59e536ee5c13
Create Date: 2025-12-08 17:58:28.772586

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fc8c9fb17c0'
down_revision = '59e536ee5c13'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('budget', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('locked_budget', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('max_drawdown_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('risk_per_trade', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('min_rr_ratio', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('session_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('total_trades', sa.Integer(), nullable=True),
    sa.Column('winning_trades', sa.Integer(), nullable=True),
    sa.Column('macro_strategy_id', sa.UUID(), nullable=True),
    sa.Column('micro_strategy_id', sa.UUID(), nullable=True),
    sa.Column('macro_timeframe', sa.String(length=10), nullable=True),
    sa.Column('micro_timeframe', sa.String(length=10), nullable=True),
    sa.Column('active_order_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_signal_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['active_order_id'], ['paper_orders.id'], ),
    sa.ForeignKeyConstraint(['macro_strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['micro_strategy_id'], ['strategies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('log_text', sa.String(), nullable=True),
    sa.Column('visual_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('meta_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['trading_agents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_logs_timestamp'), 'agent_logs', ['timestamp'], unique=False)
    op.alter_column('strategies', 'python_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('strategies', 'python_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_agent_logs_timestamp'), table_name='agent_logs')
    op.drop_table('agent_logs')
    op.drop_table('trading_agents')
    # ### end Alembic commands ###
