"""add_trailing_stop_columns

Revision ID: 6344ff9c9831
Revises: 69555bb7884a
Create Date: 2025-12-03 02:49:04.416967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6344ff9c9831'
down_revision = '69555bb7884a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
