"""add_trailing_stop_fields

Revision ID: 69555bb7884a
Revises: 8763033c6402
Create Date: 2025-12-03 02:19:19.919146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69555bb7884a'
down_revision = '8763033c6402'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_orders', sa.Column('is_trailing_stop', sa.Boolean(), nullable=True))
    op.add_column('paper_orders', sa.Column('trailing_percent', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('paper_positions', sa.Column('is_trailing_stop', sa.Boolean(), nullable=True))
    op.add_column('paper_positions', sa.Column('trailing_percent', sa.Numeric(precision=5, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_positions', 'trailing_percent')
    op.drop_column('paper_positions', 'is_trailing_stop')
    op.drop_column('paper_orders', 'trailing_percent')
    op.drop_column('paper_orders', 'is_trailing_stop')
    # ### end Alembic commands ###
