"""add_user_api_keys

Revision ID: 76adf566ecf3
Revises: 3ffe64f1f3fd
Create Date: 2025-12-03 18:44:09.238414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76adf566ecf3'
down_revision = '3ffe64f1f3fd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
