"""add_tp_sl_columns

Revision ID: 8763033c6402
Revises: f707aa8389c4
Create Date: 2025-12-03 00:11:49.912971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8763033c6402'
down_revision = 'f707aa8389c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_orders', sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('paper_orders', sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('paper_positions', sa.Column('stop_loss', sa.Numeric(precision=20, scale=8), nullable=True))
    op.add_column('paper_positions', sa.Column('take_profit', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_positions', 'take_profit')
    op.drop_column('paper_positions', 'stop_loss')
    op.drop_column('paper_orders', 'take_profit')
    op.drop_column('paper_orders', 'stop_loss')
    # ### end Alembic commands ###
