"""Add strategy type

Revision ID: 878412fc4431
Revises: c888accfe36e
Create Date: 2025-12-04 01:24:28.547215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878412fc4431'
down_revision = 'c888accfe36e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('strategies', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('strategies', 'type')
    # ### end Alembic commands ###
