"""add_locked_balance

Revision ID: badfc5a4e2fc
Revises: e0c89cf3146e
Create Date: 2025-12-03 17:22:56.899208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badfc5a4e2fc'
down_revision = 'e0c89cf3146e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_accounts', sa.Column('locked_balance', sa.Numeric(precision=20, scale=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_accounts', 'locked_balance')
    # ### end Alembic commands ###
