"""add_risk_params

Revision ID: c888accfe36e
Revises: 76adf566ecf3
Create Date: 2025-12-03 19:35:53.137085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c888accfe36e'
down_revision = '76adf566ecf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('active_strategies', sa.Column('risk_per_trade', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('active_strategies', sa.Column('risk_reward_ratio', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('active_strategies', sa.Column('stop_loss_percent', sa.Numeric(precision=5, scale=4), nullable=True))
    op.add_column('active_strategies', sa.Column('use_trailing_stop', sa.Boolean(), nullable=True))
    op.add_column('active_strategies', sa.Column('trailing_stop_percent', sa.Numeric(precision=5, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('active_strategies', 'trailing_stop_percent')
    op.drop_column('active_strategies', 'use_trailing_stop')
    op.drop_column('active_strategies', 'stop_loss_percent')
    op.drop_column('active_strategies', 'risk_reward_ratio')
    op.drop_column('active_strategies', 'risk_per_trade')
    # ### end Alembic commands ###
