"""Add folder to UserDocument

Revision ID: d67682b47b46
Revises: 878412fc4431
Create Date: 2025-12-04 22:17:04.098972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67682b47b46'
down_revision = '878412fc4431'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_documents', sa.Column('folder', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_documents', 'folder')
    # ### end Alembic commands ###
