"""add_strategy_id

Revision ID: db1ac8836ab5
Revises: badfc5a4e2fc
Create Date: 2025-12-03 17:23:52.881487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db1ac8836ab5'
down_revision = 'badfc5a4e2fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper_orders', sa.Column('strategy_id', sa.UUID(), nullable=True))
    op.add_column('paper_positions', sa.Column('strategy_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper_positions', 'strategy_id')
    op.drop_column('paper_orders', 'strategy_id')
    # ### end Alembic commands ###
