"""add_paper_trading_models

Revision ID: f707aa8389c4
Revises: 0e81f7a6efad
Create Date: 2025-12-02 23:42:54.772614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f707aa8389c4'
down_revision = '0e81f7a6efad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('paper_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('amount', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('size', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('leverage', sa.Integer(), nullable=True),
    sa.Column('liquidation_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('margin', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_trades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('fee_currency', sa.String(), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['paper_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paper_trades')
    op.drop_table('paper_positions')
    op.drop_table('paper_orders')
    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
